/*
 * Copyright 2025 HM Revenue & Customs
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package uk.gov.hmrc.test.ui.specs

import org.scalatest.matchers.should.Matchers
import org.scalatest.featurespec.AnyFeatureSpec
import uk.gov.hmrc.test.ui.cucumber.stepdefs.Hooks.{And, Given, Then, When}

class ContactDetailsAndRegistrationSpec extends AnyFeatureSpec with Matchers {

  Feature("Contact details for the filing member") {

    Scenario("1 - Create a new subscription with UPE NoID Flow and NFM No Id flow to validate Contact Details") {
      Given("Organisation User logs in as upe with credId ContactDetails for Pillar2")
      Then("I should be on UPE business page")
      When("I select option No and continue to next")
      Then("I should navigate to input-upe-name page")
      When("I enter UPE name as Test")
      When("I enter Address as:")
      When("I enter UPE Person/Team name as UPE Test")
      When("I enter UPE Email address as test&upe@email.com")
      When("I select option Yes and continue to next")
      And("I enter Phone Number as 123456")
      And("I click on Continue button")
      When("I click Add filing member details link")
      When("I select No option and continue to next")
      When("I click Add further group details link")
      When("I select option In the UK and outside the UK in further details group status page")
      When("I enter account period as:")
      And("I click on Continue button")
      Then("The Task Add contact details status should be Not started")
      When("I click Add contact details link")
      Then("I should navigate to Contact details guidance page")
      And("The caption must be Contact details")
      When("I click on Continue button")
      Then("I should navigate to Contact details display page")
      When("I select option No and continue to next")
      Then("I should navigate to Contact details input name page")
      And("The caption must be Contact details")
      When("I enter Contact Name as Contact Name Test")
      Then("I should navigate to Contact details input email page")
      When("I enter Contact Email as testContact@email.com")
      Then("I should navigate to Contact details phone page")
      When("I select option No and continue to next")
      Then("I should navigate to Second Contact details page")
      When("I select back link")
      Then("I should navigate to Contact details phone page")
      When("I select option Yes and continue to next")
      Then("I should navigate to Contact details input phone page")
      When("I enter Contact Phone as 1234554")
      And("I click on Continue button")
      Then("I should navigate to Second Contact details page")
      When("I select option No and continue to next")
      Then("I should navigate to Contact address input page")
      When("I select back link")
      Then("I should navigate to Second Contact details page")
      When("I select option Yes and continue to next")
      Then("I should navigate to Second Contact name page")
      When("I enter Second Contact Name as Second Contact Name Test")
      Then("I should navigate to Second Contact email page")
      When("I enter Second Contact Email as secondContact@email.com")
      Then("I should navigate to Second Contact number page")
      When("I select option Yes and continue to next")
      Then("I should navigate to Second Contact Input page")
      When("I enter Second Contact Input as 1234554")
      Then("I should navigate to Contact address input page")
      When("I enter Address as:")
      Then("I should navigate to Contact details Check answers page")
      When("I select back link")
      Then("I should be on Contact address input page")
      When("I select back link")
      Then("I should be on Second Contact Input page")
      When("I select back link")
      Then("I should be on Second Contact number page")
      When("I select back link")
      When("I select back link")
      When("I select back link")
      Then("I should navigate to Second Contact details page")
      When("I select back link")
      When("I select back link")
      When("I select back link")
      When("I select back link")
      When("I select back link")
      When("I select back link")
      Then("I should navigate to Contact details display page")
      When("I select back link")
      Then("I should navigate to Contact details guidance page")
      When("I select back link")
      Then("I should navigate to Task list page")
    }

    Scenario("2 - Check you Answers Page Validations") {
      Given("Organisation User navigates to Contact Details check your answer page with credId ContactDetails")
      Then("I should be on Contact details Check answers page")
      When("I click on change link for Contact Name")
      And("I enter Contact Name as Contact $ Name Change")
      Then("I should navigate to Contact details Check answers page")
      When("I click on change link for Email address")
      And("I enter Contact Email as email&change@test.com")
      Then("I should navigate to Contact details Check answers page")
      When("I click on change link for Phone number")
      And("I enter Contact Phone as 1234555")
      When("I click on change link for Second Contact Name")
      And("I enter Second Contact Name as Second Contact Name Change")
      When("I click on change link for Second Contact Email")
      And("I enter Second Contact Email as secondContact&change@email.com")
      When("I click on change link for Second Contact Phone number")
      And("I enter Contact Phone as 71235643")
      When("I click on change link for Address")
      And("I enter Address Line 1 as Address Change")
      And("I click on Continue button")
      Then("I should see details as below:")
      And("I click on Continue button")
      When("I click Check your answers before submitting your registration link")
      Then("I should be on Review answers page")
      And("I should see details as below:")
      And("I should see row 12 with key Contact name and value Contact $ Name Change")
      And("I should see row 13 with key Email address and value email&change@test.com")
      And("I should see row 14 with key Can we contact the primary contact by phone? and value Yes")
      And("I should see row 15 with key Primary phone number and value 123455")
      And("I should see row 19 with key Can we contact the secondary contact by phone? and value Yes")
      And("I should see row 21 with key Address and value Address Change")
      When("I click Report Pillar 2 Top-up Taxes link")
      Then("I should navigate to Task list page")
      When("I click Edit contact details link")
      Then("I should navigate to Contact details guidance page")
      When("I click on Continue button")
      Then("I should navigate to Contact details display page")
      When("I select option Yes and continue to next")
      Then("I should navigate to Second Contact details page")
      When("I select option No and continue to next")
      Then("I should navigate to Contact address input page")
      When("I click on Continue button")
      Then("I should be on Contact details Check answers page")
      And("I click on Continue button")
      When("I click Check your answers before submitting your registration link")
      Then("I should be on Review answers page")
    }

    Scenario("3 - Contact details pages Error validations and Registration Confirmation Page Validations") {
      Given("I clear the cache")
      Given("Organisation User logs in without Pillar2 enrolment")
      When("I select option No and continue to next")
      Then("I should navigate to input-upe-name page")
      When("I enter UPE name as Test")
      When("I enter Address as:")
      When("I enter UPE Person/Team name as UPE Test")
      When("I enter UPE Email address as test&upe@email.com")
      When("I select option Yes and continue to next")
      And("I enter Phone Number as 123456")
      And("I click on Continue button")
      When("I click Add filing member details link")
      When("I select Yes option and continue to next")
      When("I select option No and continue to next")
      When("I enter NFM name as Test")
      When("I enter Address as:")
      When("I enter NFM Contact name as Contact NFM Test")
      When("I enter NFM Contact Email as testNFM@email.com")
      When("I select option Yes and continue to next")
      When("I enter NFM Phone Number as 12345678")
      And("I click on Continue button")
      When("I click Add further group details link")
      When("I select option In the UK and outside the UK in further details group status page")
      When("I enter account period as:")
      And("I click on Continue button")
      When("I click Add contact details link")
      When("I click on Continue button")
      Then("I should navigate to Contact details display page")
      When("I click on Continue button")
      Then("I should see error message Select yes if you want to use this as your primary contact on the Contact details display Page")
      When("I select option No and continue to next")
      Then("I should navigate to Contact details input name page")
      When("I enter Contact Details Name as Test ContactName")
      And("I click on Continue button")
      Then("I should navigate to Contact details input email page")
      When("I click on Continue button")
      When("I enter Contact Email as testContact@email.com")
      And("I click on Continue button")
      Then("I should navigate to Contact details phone page")
      When("I click on Continue button")
      When("I select option Yes and continue to next")
      Then("I should navigate to Contact details input phone page")
      When("I click on Continue button")
      When("I enter NFM Phone Number as 12345343")
      When("I click on Continue button")
      Then("I should navigate to Second Contact details page")
      When("I click on Continue button")
      When("I select option Yes and continue to next")
      Then("I should navigate to Second Contact name page")
      When("I enter Second Contact Name as Test secondName")
      And("I click on Continue button")
      Then("I should navigate to Second Contact email page")
      When("I enter Second Contact Email as testContact@email.com")
      And("I click on Continue button")
      When("I select option Yes and continue to next")
      Then("I should navigate to Second Contact Input page")
      When("I click on Continue button")
      When("I enter NFM Phone Number as 1234567")
      When("I click on Continue button")
      Then("I should navigate to Contact address input page")
      When("I enter Address as:")
      Then("I should be on Contact details Check answers page")
      And("I click on Continue button")
      When("I click Check your answers before submitting your registration link")
      Then("I should navigate to Review answers page")
      And("I click on Save&Continue button")
      Then("I should be redirect to Registration processing page")
      And("I should navigate to Registration confirmation page")
      When("I click report and manage your Pillar 2 Top-up Taxes link")
      Then("I should be on Dashboard page")
      And("I click the browser back button")
    }

    Scenario("4 - Validate subscription journey from knock back page for duplicate details on registration for UPE and NFM GRS flows, verify registration confirmation page.") {
      Given("Organisation User logs in without Pillar2 enrolment")
      When("I select option Yes and continue to next")
      Then("I should be on UPE entity type page")
      When("I select option UK limited company and continue to GRS page")
      When("I registered successfully with BV enabled")
      And("I click on Save&Continue button")
      When("I click Add filing member details link")
      When("I select Yes option and continue to next")
      When("I select option Yes and continue to next")
      When("I select option UK limited company and continue to GRS page")
      When("I registered successfully with BV enabled")
      And("I click on Save&Continue button")
      When("I click Add further group details link")
      When("I select option Only in the UK in further details group status page")
      When("I enter account period as:")
      And("I click on Continue button")
      When("I click Add contact details link")
      Then("I should navigate to Contact details guidance page")
      When("I click on Continue button")
      When("I enter Contact Name as Contact Name Test")
      When("I enter Contact Email as testContact@email.com")
      When("I select option Yes and continue to next")
      When("I enter Contact Phone as 1234554")
      When("I select option No and continue to next")
      When("I enter Address as:")
      Then("I should navigate to Contact details Check answers page")
      And("I click on Continue button")
      When("I click Check your answers before submitting your registration link")
      Then("I should navigate to Review answers page")
      And("I click on Save&Continue button")
      Then("I should navigate to Registration Duplication KB Page")
      And("I click on Save&Continue button")
      When("I select No option and continue to next")
      Then("I should navigate to Review answers page")
      And("I click on Save&Continue button")
      Then("I should be redirect to Registration processing page")
      Then("I should navigate to Registration confirmation page")
      And("I click the browser back button")
      Then("I should navigate to Registration return error page")
      And("I click report and manage your Pillar 2 Top-up Taxes. link")
      And("I should be on Dashboard page")
      And("I click the browser back button")
      Then("I should be on Registration return error page")
      And("I click Sign out link")
      When("Organisation User logs in with existing entity group HMRC-PILLAR2-ORG, PLRID and XMPLR0012345674 for Pillar2 service")
      Then("I should be on Dashboard page")
    }

    Scenario("5 - Validate Yes journey from knock back page for duplicate details on registration for UPE and NFM GRS flows") {
      Given("Organisation User logs in without Pillar2 enrolment")
      When("I select option Yes and continue to next")
      Then("I should be on UPE entity type page")
      When("I select option UK limited company and continue to GRS page")
      When("I registered successfully with BV enabled")
      And("I click on Save&Continue button")
      When("I click Add filing member details link")
      When("I select Yes option and continue to next")
      When("I select option Yes and continue to next")
      When("I select option UK limited company and continue to GRS page")
      When("I registered successfully with BV enabled")
      And("I click on Save&Continue button")
      When("I click Add further group details link")
      When("I select option In the UK and outside the UK in further details group status page")
      When("I enter account period as:")
      And("I click on Continue button")
      When("I click Add contact details link")
      Then("I should navigate to Contact details guidance page")
      When("I click on Continue button")
      When("I enter Contact Name as Contact Name Test")
      When("I enter Contact Email as testContact@email.com")
      When("I select option Yes and continue to next")
      When("I enter Contact Phone as 1234554")
      When("I select option No and continue to next")
      When("I enter Address as:")
      Then("I should navigate to Contact details Check answers page")
      And("I click on Continue button")
      When("I click Check your answers before submitting your registration link")
      Then("I should navigate to Review answers page")
      And("I click on Save&Continue button")
      Then("I should navigate to Registration Duplication KB Page")
      When("I click Report Pillar 2 Top-up Taxes link")
      Then("The Task Edit filing member details status should be Completed")
      When("I click Check your answers before submitting your registration link")
      Then("I should navigate to Review answers page")
      And("I click on Save&Continue button")
      Then("I should navigate to Registration Duplication KB Page")
      When("I select Yes option and continue to next")
      Then("I should navigate to NFM details page")
      When("I select option No and continue to next")
      When("I enter NFM name as NFM Test KB")
      When("I enter Address as:")
      When("I click on Continue button")
      When("I enter NFM Contact name as Contact CYA")
      When("I enter NFM Contact Email as testcya@email.com")
      Then("I should navigate to NFM Phone page")
      When("I select option No and continue to next")
      Then("I should navigate to NFM Check your answers page")
      When("I click on Continue button")
      Then("I should be on Task list page")
      When("I click Check your answers before submitting your registration link")
      Then("I should navigate to Review answers page")
      And("I click on Save&Continue button")
      Then("I should be redirect to Registration processing page")
      And("I should navigate to Registration confirmation page")
    }

    Scenario("6 - UPE No Id journey navigation to registration in progress page") {
      Given("Organisation User logs in without Pillar2 enrolment")
      Then("I should be on UPE business page")
      When("I select option No and continue to next")
      Then("I should navigate to input-upe-name page")
      When("I enter UPE name as Medium Processing Corp")
      Then("I should navigate to input-upe-address page")
      When("I enter Address as:")
      And("I click on Continue button")
      Then("I should navigate to UPE Contact person/team Name page")
      When("I enter UPE Person/Team name as Medium Processing")
      Then("I should navigate to UPE Contact Email page")
      When("I enter UPE Email address as testcontactupe@email.com")
      Then("I should navigate to UPE Phone page")
      When("I select option Yes and continue to next")
      Then("I should navigate to input phone page")
      And("I enter Phone Number as 1234569")
      Then("I should be on Check your answers page")
      When("I click on Continue button")
      Then("I should navigate to Task list page")
      When("I click Add filing member details link")
      Then("I should navigate to NFM registration page")
      When("I select No option and continue to next")
      Then("I should navigate to Task list page")
      And("The Task Edit filing member details status should be Completed")
      When("I click Add further group details link")
      Then("I should navigate to MNE or domestic page")
      When("I select option In the UK and outside the UK in further details group status page")
      And("I click on Continue button")
      Then("I should navigate to Group accounting period page")
      When("I enter account period as:")
      Then("I should navigate to FD check your answers page")
      And("I click on Continue button")
      Then("I should navigate to Task list page")
      When("I click Add contact details link")
      Then("I should navigate to Contact details guidance page")
      When("I click on Continue button")
      When("I select option Yes and continue to next")
      Then("I should navigate to Second Contact details page")
      When("I select option No and continue to next")
      Then("I should navigate to Contact address input page")
      When("I enter Address as:")
      Then("I should navigate to Contact details Check answers page")
      And("I click on Continue button")
      When("I click Check your answers before submitting your registration link")
      Then("I should navigate to Review answers page")
      And("I click on Save&Continue button")
      Then("I should navigate to Registration confirmation page")
      And("I click report and manage your Pillar 2 Top-up Taxes link")
      Then("I should be on Registration In Progress page")
      When("I refresh the registration in progress page")
      Then("I should be on Dashboard page")
    }
  }
}
