package uk.gov.hmrc.test.ui.specs
import org.scalatest.matchers.should.Matchers

import org.scalatest.featurespec.AnyFeatureSpec
import uk.gov.hmrc.test.ui.cucumber.stepdefs.Hooks.{And, Given, Then, When}
class RFMGRSflowPagesSpec extends AnyFeatureSpec with Matchers {

  Feature("RFM Ultimate Parent Entity and New nominated Filling Member GRS journey") {

    Scenario("1 - Verify RFM GRS journey when New NFM is based in UK - UK limited company") {
      Given("Organisation User logs in without Pillar2 enrolment")
      And("I access RFM start page")
      And("I click on Continue button")
      When("I provide RFM pillar2 id as XMPLR0123456789")
      And("I click on Continue button")
      When("I enter registration date as:")
      Then("I should be on RFM CYA Page")
      When("I click on Save&Continue button")
      Then("I should be on RFM Saving Progress Page")
      When("I click on Continue button")
      Then("I should be on RFM Corp Position Page")
      When("I click on Continue button")
      When("I select corp position as NFM")
      Then("I should be on New NFM guidance page")
      When("I click on Continue button")
      Then("I should be on RFM registered in UK page")
      And("I click on Continue button")
      And("I select option Yes and continue to next")
      Then("I should be on RFM UK based entity type page")
      When("I click on Continue button")
      When("I select option UK limited company and continue to GRS page")
      Then("I should navigate to RFM UK limited Company GRSPage")
      When("I registered successfully with BV enabled")
      And("I click on Save&Continue button")
      Then("I should be on RFM Contact Guidance page")
    }

    Scenario("2 - Verify that New NFM can replace existing FM through GRS registration flow on the Pillar 2 account and validations") {
      Given("Organisation User logs in without Pillar2 enrolment")
      And("I access RFM start page")
      And("I click on Continue button")
      When("I provide RFM pillar2 id as XMPLR0123456789")
      When("I enter registration date as:")
      Then("I should be on RFM CYA Page")
      When("I click on Save&Continue button")
      When("I click on Continue button")
      When("I select corp position as NFM")
      When("I click on Continue button")
      And("I select option Yes and continue to next")
      Then("I should be on RFM UK based entity type page")
      When("I select option UK limited company and continue to GRS page")
      And("I click on Save&Continue button")
      Then("I should be on RFM Contact Guidance page")
      And("I click on Continue button")
      Then("I should navigate to RFM Contact Detail Page")
      When("I provide RFM contact name as RFM test contact")
      When("I provide RFM contact email as rfm@email.com")
      And("I select option Yes and continue to next")
      When("I provide RFM contact number as 01632960001")
      And("I select option No and continue to next")
      When("I enter Address as:")
      Then("I should navigate to RFM Final Review Page")
      When("I click change link for RFM Change Second Contact Preference")
      And("I select option Yes and continue to next")
      When("I provide RFM contact name as RFM second test contact")
      When("I provide RFM contact email as rfmsecondcontact@email.com")
      When("I select option Yes and continue to next")
      When("I provide RFM second contact number as 09872960001")
      Then("I should navigate to RFM Final Review Page")
      And("I should see details as below:")
      When("I click change link for RFM New NFM Name")
      And("I provide RFM contact name as RFM test contact change")
      And("I should see the row 5 value RFM test contact change")
      When("I click change link for RFM New RFM CYA Change Contact preference")
      And("I select option No and continue to next")
      When("I click change link for RFM Change Address")
      And("I enter Address Line 1 as Address Line 1 CYA change")
      And("I click on Continue button")
      Then("I should navigate to RFM Final Review Page")
      And("I should see the row 13 value Address Line 1 CYA change")
      And("I should see Print this page link on Review answers page")
      And("I click on Continue button")
      And("I should be redirect to RFM processing page")
      Then("I should navigate to RFM Confirmation Page")
    }

    Scenario("3 - User registration as Limited liability partnership failed with party type mismatch error") {
      Given("Organisation User logs in without Pillar2 enrolment")
      And("I access RFM start page")
      And("I click on Continue button")
      When("I provide RFM pillar2 id as XMPLR0123456789")
      When("I enter registration date as:")
      Then("I should be on RFM CYA Page")
      When("I click on Save&Continue button")
      And("I click on Continue button")
      When("I select corp position as NFM")
      When("I click on Continue button")
      And("I select option Yes and continue to next")
      When("I select option Limited liability partnership and continue to GRS page")
      Then("I should navigate to RFM LLP GRS page")
      When("registration is unsuccessful with party type mismatch error")
      And("I click on Save&Continue button")
      Then("I should be on RFM GRS Registration Mismatch Error Page")
      When("I click go back to select the entity type link")
      Then("I should be on RFM UK based entity type page")
      When("I select option Limited liability partnership and continue to GRS page")
      Then("I should navigate to RFM LLP GRS page")
    }

    Scenario("4 - User registration as UK limited company failed with identifiers mismatch error and entity type page validation") {
      Given("Organisation User logs in without Pillar2 enrolment")
      And("I access RFM start page")
      And("I click on Continue button")
      When("I provide RFM pillar2 id as XMPLR0123456789")
      When("I enter registration date as:")
      When("I click on Save&Continue button")
      And("I click on Continue button")
      When("I select corp position as NFM")
      And("I click on Continue button")
      And("I select option Yes and continue to next")
      When("I select option UK limited company and continue to GRS page")
      Then("I should navigate to RFM UK limited Company GRSPage")
      When("registration is unsuccessful with identifiers not match error")
      And("I click on Save&Continue button")
      Then("I should be on RFM GRS Registration Not Called Error Page")
      When("I click Go back to select the entity type link")
      Then("I should be on RFM UK based entity type page")
      When("I select option Entity type not listed and continue to Name page")
      Then("I should be on RFM New NFM Contact Name Page")
    }
  }
}
