/*
 * Copyright 2025 HM Revenue & Customs
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import org.scalatest.matchers.should.Matchers
import org.scalatest.featurespec.AnyFeatureSpec

class RFMnfmNoIDFlowSpec extends AnyFeatureSpec with Matchers {

  Feature("RFM CYA - NFM No ID flow") {

    Scenario("1 - Verify RFM journey for NFM No Id flow until check your answers page and validate that previously entered data is pre populated") {
      Given("Organisation User logs in with rfm URL to Pillar2")
      And("I access RFM start page")
      And("I click on Continue button")
      When("I provide RFM pillar2 id as XMPLR0123456789")
      When("I enter registration date as:")
      Then("I should be on RFM CYA Page")
      When("I click on Save&Continue button")
      Then("I should be on RFM Saving Progress Page")
      When("I click on Continue button")
      Then("I should be on RFM Corp Position Page")
      And("I click on Continue button")
      When("I select corp position as NFM")
      Then("I should be on New NFM guidance page")
      When("I click on Continue button")
      Then("I should be on RFM registered in UK page")
      When("I select option No and continue to next")
      Then("I should navigate to RFM New NFM Contact Name Page")
      When("I provide RFM New NFM Name as Test CYA")
      Then("I should navigate to RFM New NFM Contact Address Page")
      And("I enter Address Line 1 as Address Line 1 CYA")
      And("I enter City as City CYA")
      And("I enter Postal Code as EH5 5WY")
      And("I enter Country as Australia")
      And("I click on Country selected")
      And("I click on Continue button")
      Then("I should be on RFM No ID CYA Page")
      When("I click change link for RFM New NFM Name")
      Then("I should navigate to RFM New NFM Contact Name Change")
      When("I provide RFM New NFM Name as New NFM Name Change")
      Then("I should navigate to RFM No ID Change CYA Page")
      When("I click on Continue button")
      Then("I should navigate to RFM Contact Guidance page")
      And("I click Sign out link")
    }

    Scenario("2 - Validating RFM final submission for RFM as selecting UPE then changed to NFM No ID journey") {
      Given("I clear the cache")
      When("Organisation User logs in with rfm URL to Pillar2")
      And("I access RFM start page")
      And("I click on Continue button")
      When("I provide RFM pillar2 id as XMPLR0123456789")
      When("I enter registration date as:")
      When("I click on Save&Continue button")
      When("I click on Continue button")
      When("I select corp position as UPE")
      And("I click on Continue button")
      When("I provide RFM contact name as RFM test contact")
      When("I provide RFM contact email as rfm@email.com")
      Then("I should navigate to RFM Contact Number Page")
      When("I select option No and continue to next")
      And("I select option No and continue to next")
      When("I enter Address as:")
      Then("I should navigate to RFM Final Review Page")
      When("I click change link for RFM Corporate Position")
      When("I select corp position as NFM")
      And("I click on Continue button")
      When("I select option No and continue to next")
      And("I click on Continue button")
      When("I provide RFM New NFM Name as Test CYA")
      Then("I should navigate to RFM New NFM Contact Address Page")
      When("I enter Address as:")
      Then("I should be on RFM No ID CYA Page")
      And("I click on Continue button")
      Then("I should navigate to RFM Final Review Page")
      When("I select back link")
      Then("I should be on RFM No ID CYA Page")
      And("I click on Continue button")
      Then("I should navigate to RFM Final Review Page")
      When("I click change link for RFM Input Name")
      When("I provide RFM New NFM Name as Test Change")
      Then("I should navigate to RFM Final Review Page")
      When("I click change link for RFM Input Address")
      And("I enter Address Line 1 as Address Line 1 Change")
      And("I enter City as City Change")
      And("I enter Postal Code as EH75WK")
      And("I click on Continue button")
      Then("I should navigate to RFM Final Review Page")
      And("I should see row 3 value Address Line 1 Change")
      And("I should see row 3 value City Change")
      And("I should see row 3 value EH75WK")
      And("I click on Continue button")
      Then("I should be redirect to RFM processing page")
      And("I should be on RFM Confirmation Page")
      When("I click the browser back button")
      Then("I should navigate to RFM No Return Back Error Page")
      And("I click report and manage your Pillar 2 Top-up Taxes link")
      Then("I should be on Dashboard page")
    }

    Scenario("3 - Validating RFM Check your answers page navigations") {
      Given("Organisation User logs in with rfm URL to Pillar2")
      And("I access RFM start page")
      And("I click on Continue button")
      When("I provide RFM pillar2 id as XMPLR0123456789")
      When("I enter registration date as:")
      When("I click on Save&Continue button")
      When("I click on Continue button")
      When("I select corp position as UPE")
      And("I click on Continue button")
      When("I provide RFM contact name as RFM test contact")
      When("I provide RFM contact email as rfm@email.com")
      When("I select option No and continue to next")
      And("I select option No and continue to next")
      When("I enter Address as:")
      Then("I should navigate to RFM Final Review Page")
      When("I click change link for RFM Corporate Position")
      And("I select corp position as NFM")
      Then("I should be on New NFM guidance page")
      And("I click on Continue button")
      Then("I should be on RFM registered in UK page")
      When("I select option Yes and continue to next")
      Then("I should be on RFM UK based entity type page")
      When("I select option UK limited company and continue to GRS page")
      Then("I should navigate to RFM UK limited Company GRSPage")
      When("I navigate back to RFM CYA Page from GRS Page")
      Then("I should navigate to RFM Final Review Page")
      When("I click change link for RFM Corporate Position")
      And("I click on Continue button")
      Then("I should be on New NFM guidance page")
      And("I click on Continue button")
      Then("I should be on RFM registered in UK page")
      And("I click on Continue button")
      Then("I should be on RFM UK based entity type page")
    }

    Scenario("4 - Validating RFM Check your answers page for UPE/NFM journey Responses") {
      Given("Organisation User logs in with rfm URL to Pillar2")
      And("I access RFM start page")
      And("I click on Continue button")
      When("I provide RFM pillar2 id as XMPLR0123456789")
      When("I enter registration date as:")
      When("I click on Save&Continue button")
      And("I access RFM corporate position page")
      When("I select corp position as UPE")
      And("I click on Continue button")
      When("I provide RFM contact name as RFM test contact")
      When("I provide RFM contact email as rfm@email.com")
      When("I select option No and continue to next")
      And("I select option No and continue to next")
      When("I enter Address as:")
      When("I click change link for RFM Corporate Position")
      When("I select corp position as NFM")
      And("I click on Continue button")
      When("I select option No and continue to next")
      When("I provide RFM New NFM Name as Test CYA")
      When("I enter Address as:")
      Then("I should be on RFM No ID CYA Page")
      And("I click on Continue button")
      Then("I should navigate to RFM Final Review Page")
      When("I select back link")
      Then("I should be on RFM No ID CYA Page")
      And("I click on Continue button")
      Then("I should navigate to RFM Final Review Page")
      When("I click change link for RFM Input Name")
      When("I provide RFM New NFM Name as Test Change")
      Then("I should navigate to RFM Final Review Page")
      When("I click change link for RFM Input Address")
      And("I enter Address Line 1 as Address Line 1 Change")
      And("I enter City as City Change")
      And("I enter Postal Code as EH75WK")
      And("I click on Continue button")
      Then("I should navigate to RFM Final Review Page")
      And("I should see details as below:")
      When("I click change link for RFM Corporate Position")
      When("I select corp position as UPE")
      And("I should see row 1 value Ultimate Parent Entity (UPE)")
      When("I click change link for RFM Corporate Position")
      When("I select corp position as NFM")
      And("I click on Continue button")
      When("I select option Yes and continue to next")
      When("I select option UK limited company and continue to GRS page")
      Then("I should navigate to RFM UK limited Company GRSPage")
      When("I registered successfully with BV enabled")
      And("I click on Save&Continue button")
      Then("I should be on RFM Contact Guidance page")
      And("I click on Continue button")
      Then("I should navigate to RFM Contact Detail Page")
      And("I click on Continue button")
      Then("I should navigate to RFM Contact Email Page")
      And("I click on Continue button")
      Then("I should navigate to RFM Contact Number Page")
      And("I click on Continue button")
      Then("I should navigate to RFM Second Contact Question Page")
      And("I click on Continue button")
      Then("I should be on RFM Contact Address Page")
      When("I click on Continue button")
      Then("I should navigate to RFM Final Review Page")
    }

    Scenario("5 - Verify that New NFM can replace existing FM through NO ID flow on the Pillar 2 account") {
      Given("Organisation User logs in without Pillar2 enrolment")
      And("I access RFM start page")
      And("I click on Continue button")
      When("I provide RFM pillar2 id as XMPLR0123456789")
      When("I enter registration date as:")
      When("I click on Save&Continue button")
      When("I click on Continue button")
      When("I select corp position as NFM")
      When("I click on Continue button")
      And("I select option No and continue to next")
      When("I provide RFM New NFM Name as Test CYA")
      When("I enter Address as:")
      And("I click on Continue button")
      And("I click on Continue button")
      When("I provide RFM contact name as RFM test contact")
      When("I provide RFM contact email as rfm@email.com")
      And("I select option No and continue to next")
      And("I select option No and continue to next")
      When("I enter Address as:")
      Then("I should navigate to RFM Final Review Page")
      And("I click on Continue button")
      Then("I should be redirect to RFM processing page")
      And("I should be on RFM Confirmation Page")
      When("I click report and manage your group's Pillar 2 Top-up Taxes link")
      Then("I should be on Dashboard page")
    }

    Scenario("6 - Verify that UPE can replace existing FM on the Pillar 2 account") {
      Given("Organisation User logs in without Pillar2 enrolment")
      And("I access RFM start page")
      And("I click on Continue button")
      When("I provide RFM pillar2 id as XMPLR0123456789")
      When("I enter registration date as:")
      When("I click on Save&Continue button")
      And("I click on Continue button")
      When("I select corp position as UPE")
      When("I click on Continue button")
      When("I provide RFM contact name as RFM test contact")
      When("I provide RFM contact email as rfm@email.com")
      And("I select option Yes and continue to next")
      When("I provide RFM contact number as 01632960001")
      And("I select option Yes and continue to next")
      And("I click on Continue button")
      When("I provide RFM contact name as RFM second test contact")
      When("I click on Continue button")
      When("I provide RFM contact email as rfmsecondcontact@email.com")
      Then("I click on Continue button")
      When("I select option Yes and continue to next")
      When("I provide RFM second contact number as 09872960001")
      When("I enter Address as:")
      When("I click on change link for Contact Name")
      When("I enter Contact Name as 400")
      And("I click on Continue button")
      Then("I should be redirected to RFM processing page or Amend API error Page for RFM")
      When("I click to replace the filing member for a Pillar 2 Top-up Taxes account to try again link")
      Then("I should navigate to RFM Final Review Page")
      When("I click on change link for Contact Name")
      When("I enter Contact Name as test name")
      And("I click on Continue button")
      And("I should navigate to RFM Confirmation Page")
      When("I click report and manage your group's Pillar 2 Top-up Taxes link")
      Then("I should be on Dashboard page")
    }
  }
}
